# Generated by Django 4.2.16 on 2024-09-11 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(help_text='The file path', max_length=1000)),
                ('file_type', models.CharField(choices=[('image/jpg', 'JPG'), ('image/png', 'PNG'), ('video/mp4', 'MP4'), ('gif/gif', 'GIF')], default='image/jpg', help_text='The file type', max_length=20)),
                ('weight', models.FloatField(default=1.0, help_text='Weight for random choice')),
            ],
            options={
                'db_table': 'core_media',
            },
        ),
        migrations.CreateModel(
            name='Seiyuu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Seiyuu Name, exmaple: 前田佳織里', max_length=20)),
                ('screen_name', models.CharField(blank=True, help_text='Bot account screen name, example: kaorin__bot', max_length=20, null=True)),
                ('id_name', models.CharField(blank=True, help_text='Seiyuu short name, example: kaorin', max_length=20, null=True)),
                ('activated', models.BooleanField(default=True, help_text='If the bot is activated')),
                ('interval', models.IntegerField(default=1, help_text='Interval between tweets in hours')),
                ('image_folder', models.CharField(blank=True, help_text='The folder name of the images', max_length=20, null=True)),
                ('hidden', models.BooleanField(default=False, help_text='If the seiyuu should be hidden from website')),
            ],
            options={
                'db_table': 'core_seiyuu',
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.CharField(help_text='Tweet ID', max_length=50, primary_key=True, serialize=False)),
                ('post_time', models.DateTimeField(blank=True, help_text='Tweet time', null=True)),
                ('data_time', models.DateTimeField(blank=True, help_text='Data collected time', null=True)),
                ('like', models.SmallIntegerField(blank=True, help_text='Likes', null=True)),
                ('rt', models.SmallIntegerField(blank=True, help_text='Retweets', null=True)),
                ('reply', models.SmallIntegerField(blank=True, help_text='number of replies', null=True)),
                ('quote', models.SmallIntegerField(blank=True, help_text='number of quotes', null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.media')),
            ],
            options={
                'db_table': 'core_tweet',
            },
        ),
        migrations.AddField(
            model_name='media',
            name='seiyuu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.seiyuu'),
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_time', models.DateTimeField(blank=True, help_text='Data collected time', null=True)),
                ('followers', models.IntegerField(blank=True, help_text='Current followers', null=True)),
                ('seiyuu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.seiyuu')),
            ],
            options={
                'db_table': 'core_followers',
            },
        ),
    ]
