# Generated by Django 4.2.23 on 2026-07-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seiyuu',
            name='auth_token',
            field=models.CharField(blank=True, help_text='The auth token in cookie when login as the account', max_length=1000, null=True),
        ),
    ]
